# Site settings

title: How to creat your project pages
header-img: img/home-bg.jpg
email: dmo7@gatech.edu
description: " Followed tutorial to be able to set up a Project Pages for the ME8883 Class"
baseurl: "/project-pages"
url: "http://matin-hub.github.io"
github_username:  matin-hub
project_repository: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
