# Site settings

title: How to creat your project pages
header-img: img/home-bg.jpg
email: dmo7@gatech.edu
description: " Followed tutorial to be able to set up a Project Pages for the ME8883 Class"
baseurl: "/ME8883_testclass"
url: "http://dmontesdeocaz.github.io"
github_username:  dmontesdeocaz
project_repository: ME8883_testclass

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
